# Generated by Django 4.2.7 on 2025-09-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themecustomization',
            name='theme',
            field=models.CharField(choices=[], max_length=10, verbose_name='Базовая тема'),
        ),
        migrations.AlterField(
            model_name='themeusage',
            name='theme',
            field=models.CharField(choices=[], max_length=10, verbose_name='Использованная тема'),
        ),
        migrations.AlterField(
            model_name='userthemepreference',
            name='theme',
            field=models.CharField(choices=[], default='school', max_length=10, verbose_name='Выбранная тема'),
        ),
    ]
