[tool.black]
line-length = 88
target-version = ['py311']
exclude = ['migrations']

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
known_first_party = ["core", "learning", "telegram_bot", "telegram_auth", "examflow_project"]

[tool.ruff]
line-length = 88
target-version = "py311"
select = ["E","F","I","UP","S","B","C4","N","ANN"]
ignore = ["ANN101","ANN102"]
exclude = ["migrations",".venv","venv","node_modules"]

[tool.mypy]
python_version = 3.11
ignore_missing_imports = true
strict = false
warn_redundant_casts = true
warn_unused_ignores = true
disable_error_code = "annotation-unchecked"
