# Render конфигурация для ExamFlow 2.0
# Обеспечивает работу 24/7 с оптимизацией для бесплатного тарифа

services:
  - type: web
    name: examflow-web
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
      python manage.py init_freemium_limits
    startCommand: |
      python manage.py runserver 0.0.0.0:$PORT
    healthCheckPath: /health/simple/
    autoDeploy: true
    envVars:
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: examflow.ru,www.examflow.ru,examflow.onrender.com
      - key: WEBSITE_URL
        value: https://examflow.ru
      - key: TELEGRAM_BOT_TOKEN
        fromDatabase:
          name: examflow-db
          property: telegram_bot_token
      - key: GEMINI_API_KEY
        fromDatabase:
          name: examflow-db
          property: gemini_api_key
      - key: DATABASE_URL
        fromDatabase:
          name: examflow-db
          property: connectionString
      - key: SECRET_KEY
        fromDatabase:
          name: examflow-db
          property: secret_key
      - key: USE_REDIS_CACHE
        value: "0"
      - key: ENVIRONMENT
        value: production
    # Настройки для бесплатного тарифа
    scaling:
      minInstances: 1
      maxInstances: 1
    # Health check настройки
    healthCheck:
      path: /health/simple/
      initialDelay: 30
      interval: 30
      timeout: 10
      threshold: 3
    # Cron задачи для keepalive
    cronJobs:
      - name: keepalive-wake
        schedule: "*/10 * * * *"  # Каждые 10 минут
        command: |
          curl -s https://examflow.ru/health/simple/ > /dev/null
      - name: keepalive-deep
        schedule: "0 */2 * * *"  # Каждые 2 часа
        command: |
          curl -s https://examflow.ru/health/ > /dev/null

  - type: worker
    name: examflow-keepalive
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      python manage.py manage_keepalive start --daemon --interval 300
    envVars:
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: examflow.ru,www.examflow.ru,examflow.onrender.com
      - key: WEBSITE_URL
        value: https://examflow.ru
      - key: TELEGRAM_BOT_TOKEN
        fromDatabase:
          name: examflow-db
          property: telegram_bot_token
      - key: GEMINI_API_KEY
        fromDatabase:
          name: examflow-db
          property: gemini_api_key
      - key: DATABASE_URL
        fromDatabase:
          name: examflow-db
          property: connectionString
      - key: SECRET_KEY
        fromDatabase:
          name: examflow-db
          property: secret_key
      - key: USE_REDIS_CACHE
        value: "0"
      - key: ENVIRONMENT
        value: production

databases:
  - name: examflow-db
    plan: free
    databaseName: examflow_production
    user: examflow_user
    # Настройки для PostgreSQL
    postgresql:
      version: "15"
    # Автоматическое резервное копирование
    backup:
      schedule: "0 2 * * *"  # Каждый день в 2:00
      retention: 7  # 7 дней