services:
  - type: web
    name: examflow-web
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn examflow_project.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DJANGO_SETTINGS_MODULE
        value: examflow_project.settings
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: examflow.onrender.com
    healthCheckPath: /health/
    
  - type: worker
    name: examflow-worker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py runbot
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DJANGO_SETTINGS_MODULE
        value: examflow_project.settings