services:
  - type: web
    name: examflow
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: |
      echo "🔄 Применяем миграции..."
      python manage.py migrate --noinput
      echo "🚀 Запускаем сервер..."
      gunicorn examflow_project.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: examflow_project.settings
      - key: PORT
        value: 10000
