services:
  - type: web
    name: examflow-web
    env: python
    buildCommand: "chmod +x build.sh && ./build.sh"
    startCommand: "chmod +x start.sh && ./start.sh"
    healthCheckPath: /healthz
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: examflow-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: examflow-redis
          property: connectionString
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: SITE_URL
        value: https://examflow.ru
      - key: DEBUG
        value: "False"
      - key: TELEGRAM_BOT_USERNAME
        value: ExamFlowBot

  - type: postgres
    name: examflow-db
    plan: free
    
  - type: redis
    name: examflow-redis
    plan: free
