# Generated by Django 4.2.7 on 2025-08-11 13:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тип экзамена')),
                ('code', models.CharField(max_length=10, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Тип экзамена',
                'verbose_name_plural': 'Типы экзаменов',
            },
        ),
        migrations.RemoveField(
            model_name='subject',
            name='code',
        ),
        migrations.RemoveField(
            model_name='task',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='task',
            name='text',
        ),
        migrations.AddField(
            model_name='subject',
            name='exam_type',
            field=models.CharField(choices=[('ЕГЭ', 'Единый государственный экзамен'), ('ОГЭ', 'Основной государственный экзамен')], default='ЕГЭ', max_length=3, verbose_name='Тип экзамена'),
        ),
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default=2, max_length=200, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprogress',
            name='user_answer',
            field=models.TextField(blank=True, verbose_name='Ответ пользователя'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название предмета'),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Тема')),
                ('code', models.CharField(max_length=20, verbose_name='Код темы')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
            },
        ),
    ]
