# Generated by Django 4.2.7 on 2025-08-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_examtype_remove_subject_code_remove_task_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(default='Задание без названия', max_length=200, verbose_name='Название задания'),
        ),
    ]
