# Generated by Django 4.2.7 on 2025-08-20 13:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_userrating_userprofile_subscription_achievement_and_more'),
    ]

    operations = [
        # Эти модели уже существуют в базе данных
        # Убираем их создание, чтобы избежать конфликта
        # migrations.CreateModel для UserRating, UserProfile, Subscription,
        # Achievement удалены
    ]
