# Generated by Django 4.2.7 on 2025-08-20 18:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_userrating_userprofile_subscription_achievement'),
    ]

    operations = [
        # Пустая миграция - таблицы уже существуют
        # Только обновляем поле difficulty в Task
        migrations.AlterField(
            model_name='task',
            name='difficulty',
            field=models.IntegerField(verbose_name='Сложность'),
        ),
    ]
