# Generated by Django 4.2.7 on 2025-08-20 18:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_alter_task_difficulty_userrating_userprofile_and_more'),
    ]

    operations = [
        # Пустая миграция - таблицы уже существуют
        # Только добавляем поле current_task_id в UserProfile если его нет
    ]
