# Generated by Django 4.2.7 on 2025-08-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userrating_userprofile_subscription_achievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='FipiTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=100, verbose_name='Предмет')),
                ('exam_type', models.CharField(max_length=10, verbose_name='Тип экзамена')),
                ('task_number', models.IntegerField(verbose_name='Номер задания')),
                ('content', models.TextField(verbose_name='Содержание задания')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Ответ')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='Объяснение')),
                ('source_url', models.URLField(blank=True, verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Задание ФИПИ',
                'verbose_name_plural': 'Задания ФИПИ',
                'unique_together': {('subject', 'exam_type', 'task_number')},
            },
        ),
        migrations.CreateModel(
            name='VoiceMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_id', models.IntegerField(verbose_name='ID задания')),
                ('audio_file', models.FileField(upload_to='voice_hints/', verbose_name='Аудио файл')),
                ('duration', models.IntegerField(verbose_name='Длительность в секундах')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Голосовое сообщение',
                'verbose_name_plural': 'Голосовые сообщения',
            },
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='user',
        ),
        migrations.DeleteModel(
            name='ExamType',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='task',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userrating',
            name='user',
        ),
        migrations.DeleteModel(
            name='Achievement',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='UserProgress',
        ),
        migrations.DeleteModel(
            name='UserRating',
        ),
    ]
