# Generated by Django 4.2.7 on 2025-08-25 06:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_fipitask_voicemessage_remove_achievement_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код предмета')),
                ('exam_type', models.CharField(choices=[('ege', 'ЕГЭ'), ('oge', 'ОГЭ')], max_length=20, verbose_name='Тип экзамена')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Текст задачи')),
                ('solution', models.TextField(blank=True, verbose_name='Решение')),
                ('answer', models.CharField(blank=True, max_length=100, verbose_name='Ответ')),
                ('difficulty', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Сложность')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='Источник')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год')),
                ('topics', models.JSONField(blank=True, default=list, verbose_name='Темы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['subject', 'difficulty', 'title'],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильно решено')),
                ('attempts', models.IntegerField(default=1, verbose_name='Количество попыток')),
                ('time_spent', models.IntegerField(default=0, verbose_name='Время в секундах')),
                ('last_attempt', models.DateTimeField(auto_now=True, verbose_name='Последняя попытка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.task', verbose_name='Задача')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_userprogress_set', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Прогресс пользователя',
                'verbose_name_plural': 'Прогресс пользователей',
                'ordering': ['-last_attempt'],
                'unique_together': {('user', 'task')},
            },
        ),
        migrations.DeleteModel(
            name='FipiTask',
        ),
        migrations.AlterUniqueTogether(
            name='reminderlog',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='reminderlog',
            name='user',
        ),
        migrations.DeleteModel(
            name='VoiceMessage',
        ),
        migrations.DeleteModel(
            name='ReminderLog',
        ),
    ]
