# Generated by Django 4.2.7 on 2025-08-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_subject_task_userprogress_delete_fipitask_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='explanation',
            field=models.TextField(
                blank=True,
                verbose_name='Объяснение'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='user_answer',
            field=models.CharField(
                blank=True,
                max_length=200,
                verbose_name='Ответ пользователя'),
        ),
    ]
