# Generated by Django 4.2.7 on 2025-09-01 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_task_explanation_userprogress_user_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('challenge_type', models.CharField(choices=[('solve_tasks', 'Решить задачи'), ('streak', 'Серия решений'), ('subject_focus', 'Фокус на предмете'), ('time_limit', 'На время')], max_length=20, verbose_name='Тип вызова')),
                ('target_value', models.IntegerField(verbose_name='Целевое значение')),
                ('reward_xp', models.IntegerField(default=50, verbose_name='Награда (XP)')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Ежедневный вызов',
                'verbose_name_plural': 'Ежедневные вызовы',
                'unique_together': {('challenge_type', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UnifiedProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('telegram_username', models.CharField(blank=True, max_length=100, verbose_name='Telegram Username')),
                ('display_name', models.CharField(max_length=100, verbose_name='Отображаемое имя')),
                ('avatar_url', models.URLField(blank=True, verbose_name='URL аватара')),
                ('notification_settings', models.JSONField(default=dict, verbose_name='Настройки уведомлений')),
                ('total_solved', models.IntegerField(default=0, verbose_name='Всего решено задач')),
                ('current_streak', models.IntegerField(default=0, verbose_name='Текущая серия')),
                ('best_streak', models.IntegerField(default=0, verbose_name='Лучшая серия')),
                ('level', models.IntegerField(default=1, verbose_name='Уровень')),
                ('experience_points', models.IntegerField(default=0, verbose_name='Очки опыта')),
                ('achievements', models.JSONField(default=list, verbose_name='Достижения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Последняя активность')),
                ('preferred_subjects', models.ManyToManyField(blank=True, to='core.subject', verbose_name='Предпочитаемые предметы')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь Django')),
            ],
            options={
                'verbose_name': 'Унифицированный профиль',
                'verbose_name_plural': 'Унифицированные профили',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='UserChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_progress', models.IntegerField(default=0, verbose_name='Текущий прогресс')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершен')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dailychallenge', verbose_name='Вызов')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unifiedprofile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Прогресс по вызову',
                'verbose_name_plural': 'Прогресс по вызовам',
                'unique_together': {('profile', 'challenge')},
            },
        ),
    ]
