# Generated by Django 4.2.7 on 2025-09-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_dailychallenge_alter_subject_exam_type_userprofile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="telegram_id",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Telegram ID"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="telegram_username",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Telegram Username"
            ),
        ),
    ]
