# Generated by Django 4.2.7 on 2025-09-01 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_unified_profile_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession', fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('telegram_id', models.BigIntegerField(
                        verbose_name='Telegram ID')), ('session_id', models.CharField(
                            max_length=100, unique=True, verbose_name='ID сессии')), ('created_at', models.DateTimeField(
                                auto_now_add=True, verbose_name='Создана')), ('last_activity', models.DateTimeField(
                                    auto_now=True, verbose_name='Последняя активность')), ('context_messages', models.JSONField(
                                        default=list, verbose_name='История сообщений')), ('max_context_length', models.IntegerField(
                                            default=10, verbose_name='Максимальная длина контекста')), ('user', models.ForeignKey(
                                                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')), ], options={
                'verbose_name': 'Сессия чата', 'verbose_name_plural': 'Сессии чата', 'indexes': [
                    models.Index(
                        fields=[
                            'telegram_id', 'session_id'], name='core_chatse_telegra_1fb75f_idx'), models.Index(
                        fields=['last_activity'], name='core_chatse_last_ac_e14ffe_idx')], }, ), ]
