# Generated by Django 4.2.7 on 2025-09-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_userprofile_telegram_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailychallenge",
            name="challenge_type",
            field=models.CharField(
                choices=[
                    ("daily_tasks", "Ежедневные задания"),
                    ("streak", "Серия правильных ответов"),
                    ("subject_focus", "Фокус на предмете"),
                    ("time_challenge", "Временной вызов"),
                ],
                max_length=20,
                verbose_name="Тип вызова",
            ),
        ),
        migrations.AlterField(
            model_name="fipidata",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("tasks", "Задания"),
                    ("theory", "Теория"),
                    ("examples", "Примеры"),
                    ("solutions", "Решения"),
                ],
                max_length=50,
                verbose_name="Тип данных",
            ),
        ),
        migrations.AlterField(
            model_name="fipidata",
            name="exam_type",
            field=models.CharField(
                choices=[("ege", "ЕГЭ"), ("oge", "ОГЭ")],
                default="ege",
                max_length=20,
                verbose_name="Тип экзамена",
            ),
        ),
        migrations.AlterField(
            model_name="fipisourcemap",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("tasks", "Задания"),
                    ("theory", "Теория"),
                    ("examples", "Примеры"),
                    ("solutions", "Решения"),
                ],
                max_length=50,
                verbose_name="Тип данных",
            ),
        ),
        migrations.AlterField(
            model_name="fipisourcemap",
            name="exam_type",
            field=models.CharField(
                choices=[("ege", "ЕГЭ"), ("oge", "ОГЭ")],
                max_length=20,
                verbose_name="Тип экзамена",
            ),
        ),
        migrations.AlterField(
            model_name="fipisourcemap",
            name="file_format",
            field=models.CharField(
                choices=[
                    ("HTML", "HTML"),
                    ("PDF", "PDF"),
                    ("DOC", "DOC"),
                    ("JSON", "JSON"),
                ],
                default="HTML",
                max_length=10,
                verbose_name="Формат файла",
            ),
        ),
        migrations.AlterField(
            model_name="fipisourcemap",
            name="priority",
            field=models.IntegerField(
                choices=[
                    (1, "Критический"),
                    (2, "Высокий"),
                    (3, "Средний"),
                    (4, "Низкий"),
                ],
                default=3,
                verbose_name="Приоритет",
            ),
        ),
        migrations.AlterField(
            model_name="fipisourcemap",
            name="update_frequency",
            field=models.CharField(
                choices=[
                    ("daily", "Ежедневно"),
                    ("weekly", "Еженедельно"),
                    ("monthly", "Ежемесячно"),
                    ("annually", "Ежегодно"),
                ],
                default="annually",
                max_length=20,
                verbose_name="Частота обновления",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="exam_type",
            field=models.CharField(
                choices=[("ege", "ЕГЭ"), ("oge", "ОГЭ"), ("other", "Другое")],
                default="ege",
                max_length=20,
                verbose_name="Тип экзамена",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="difficulty_preference",
            field=models.CharField(
                choices=[
                    ("easy", "Легкий"),
                    ("medium", "Средний"),
                    ("hard", "Сложный"),
                ],
                default="medium",
                max_length=20,
                verbose_name="Предпочитаемая сложность",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="subscription_type",
            field=models.CharField(
                choices=[
                    ("free", "Бесплатная"),
                    ("premium", "Премиум"),
                    ("pro", "Профессиональная"),
                ],
                default="free",
                max_length=20,
                verbose_name="Тип подписки",
            ),
        ),
    ]
