# Generated by Django 4.2.7 on 2025-09-02 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_chatsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='FIPIData', fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('title', models.CharField(
                        max_length=500, verbose_name='Название')), ('url', models.URLField(
                            verbose_name='URL')), ('data_type', models.CharField(
                                choices=[
                                    ('demo_variant', 'Демонстрационный вариант'), ('open_bank_task', 'Задание из открытого банка'), ('specification', 'Спецификация'), ('codifier', 'Кодификатор')], max_length=50, verbose_name='Тип данных')), ('subject', models.CharField(
                                        blank=True, max_length=100, null=True, verbose_name='Предмет')), ('content_hash', models.CharField(
                                            max_length=64, unique=True, verbose_name='Хеш содержимого')), ('content', models.TextField(
                                                blank=True, verbose_name='Содержимое')), ('collected_at', models.DateTimeField(
                                                    verbose_name='Дата сбора')), ('processed_at', models.DateTimeField(
                                                        blank=True, null=True, verbose_name='Дата обработки')), ('is_processed', models.BooleanField(
                                                            default=False, verbose_name='Обработано')), ('created_at', models.DateTimeField(
                                                                auto_now_add=True, verbose_name='Дата создания')), ('updated_at', models.DateTimeField(
                                                                    auto_now=True, verbose_name='Дата обновления')), ], options={
                'verbose_name': 'Данные ФИПИ', 'verbose_name_plural': 'Данные ФИПИ', 'ordering': ['-collected_at'], 'indexes': [
                    models.Index(
                        fields=['data_type'], name='core_fipida_data_ty_70054f_idx'), models.Index(
                        fields=['subject'], name='core_fipida_subject_2de95e_idx'), models.Index(
                        fields=['is_processed'], name='core_fipida_is_proc_020571_idx'), models.Index(
                        fields=['collected_at'], name='core_fipida_collect_725fc0_idx')], }, ), migrations.CreateModel(
            name='DataChunk', fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('chunk_text', models.TextField(
                        verbose_name='Текст чанка')), ('chunk_index', models.IntegerField(
                            verbose_name='Индекс чанка')), ('embedding', models.JSONField(
                                verbose_name='Векторное представление')), ('metadata', models.JSONField(
                                    blank=True, default=dict, verbose_name='Метаданные')), ('created_at', models.DateTimeField(
                                        auto_now_add=True, verbose_name='Дата создания')), ('source_data', models.ForeignKey(
                                            on_delete=django.db.models.deletion.CASCADE, to='core.fipidata', verbose_name='Исходные данные')), ], options={
                'verbose_name': 'Чанк данных', 'verbose_name_plural': 'Чанки данных', 'ordering': [
                    'source_data', 'chunk_index'], 'indexes': [
                    models.Index(
                        fields=['source_data'], name='core_datach_source__fcb14f_idx'), models.Index(
                        fields=['chunk_index'], name='core_datach_chunk_i_eaf57f_idx')], 'unique_together': {
                    (
                        'source_data', 'chunk_index')}, }, ), ]
