# Generated by Django 4.2.7 on 2025-09-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_fipidata_datachunk'),
    ]

    operations = [
        migrations.CreateModel(
            name='FIPISourceMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=100, unique=True, verbose_name='ID источника')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('url', models.URLField(verbose_name='URL')),
                ('data_type', models.CharField(
                    choices=[
                        ('demo_variant', 'Демонстрационный вариант'),
                        ('specification', 'Спецификация КИМ'),
                        ('codefier', 'Кодификатор'),
                        ('open_bank_task', 'Задание из открытого банка'),
                        ('methodical_material', 'Методический материал'),
                        ('news', 'Новости и анонсы'),
                        ('document', 'Официальные документы')
                    ],
                    max_length=50,
                    verbose_name='Тип данных'
                )),
                ('exam_type', models.CharField(
                    choices=[
                        ('ege', 'ЕГЭ'),
                        ('oge', 'ОГЭ'),
                        ('gve_11', 'ГВЭ-11'),
                        ('gve_9', 'ГВЭ-9'),
                        ('essay', 'Итоговое сочинение'),
                        ('interview', 'Итоговое собеседование')
                    ],
                    max_length=20,
                    verbose_name='Тип экзамена'
                )),
                ('subject', models.CharField(blank=True, max_length=100, null=True, verbose_name='Предмет')),
                ('priority', models.IntegerField(
                    choices=[
                        (1, 'Критически важные'),
                        (2, 'Высокий приоритет'),
                        (3, 'Средний приоритет'),
                        (4, 'Низкий приоритет')
                    ],
                    default=3,
                    verbose_name='Приоритет'
                )),
                ('update_frequency', models.CharField(
                    choices=[
                        ('annually', 'Ежегодно'),
                        ('monthly', 'Ежемесячно'),
                        ('weekly', 'Еженедельно'),
                        ('daily', 'Ежедневно'),
                        ('on_demand', 'По требованию')
                    ],
                    default='annually',
                    max_length=20,
                    verbose_name='Частота обновления'
                )),
                ('file_format', models.CharField(
                    choices=[
                        ('HTML', 'HTML'),
                        ('PDF', 'PDF'),
                        ('DOC', 'DOC'),
                        ('XLS', 'XLS'),
                        ('XLSX', 'XLSX')
                    ],
                    default='HTML',
                    max_length=10,
                    verbose_name='Формат файла'
                )),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('last_checked', models.DateTimeField(blank=True, null=True, verbose_name='Последняя проверка')),
                ('content_hash', models.CharField(blank=True, max_length=64, null=True, verbose_name='Хеш содержимого')),
                ('last_updated', models.DateTimeField(blank=True, null=True, verbose_name='Последнее обновление')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Источник данных ФИПИ',
                'verbose_name_plural': 'Источники данных ФИПИ',
                'ordering': ['priority', 'data_type', 'subject'],
                'indexes': [
                    models.Index(fields=['priority'], name='core_fipiso_priorit_a5e03b_idx'),
                    models.Index(fields=['data_type'], name='core_fipiso_data_ty_c59bff_idx'),
                    models.Index(fields=['exam_type'], name='core_fipiso_exam_ty_61826a_idx'),
                    models.Index(fields=['subject'], name='core_fipiso_subject_e5abb1_idx'),
                    models.Index(fields=['is_active'], name='core_fipiso_is_acti_bf791d_idx'),
                    models.Index(fields=['last_checked'], name='core_fipiso_last_ch_eaa0c4_idx'),
                ],
            },
        ),
    ]
