# Generated by Django 4.2.7 on 2025-09-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_fipisourcemap'),
    ]

    operations = [
        migrations.AddField(
            model_name='fipidata',
            name='exam_type',
            field=models.CharField(
                choices=[
                    ('ege',
                     'ЕГЭ'),
                    ('oge',
                     'ОГЭ'),
                    ('vpr',
                     'ВПР')],
                default='ege',
                max_length=20,
                verbose_name='Тип экзамена'),
        ),
    ]
