# Generated by Django 4.2.7 on 2025-09-09 15:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_add_userprofile_and_update_datachunk"),
        ("core", "0018_subscriptionlimit_usersubscription_dailyusage"),
    ]

    operations = []
