# Generated by Django 4.2.7 on 2025-09-15 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0019_merge_20250909_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailychallenge',
            name='challenge_type',
            field=models.CharField(choices=[], max_length=20, verbose_name='Тип вызова'),
        ),
        migrations.AlterField(
            model_name='dailyusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_usage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='datachunk',
            name='embedding',
            field=models.JSONField(verbose_name='Векторное представление (JSON)'),
        ),
        migrations.AlterField(
            model_name='fipidata',
            name='data_type',
            field=models.CharField(choices=[], max_length=50, verbose_name='Тип данных'),
        ),
        migrations.AlterField(
            model_name='fipidata',
            name='exam_type',
            field=models.CharField(choices=[], default='ege', max_length=20, verbose_name='Тип экзамена'),
        ),
        migrations.AlterField(
            model_name='fipisourcemap',
            name='data_type',
            field=models.CharField(choices=[], max_length=50, verbose_name='Тип данных'),
        ),
        migrations.AlterField(
            model_name='fipisourcemap',
            name='exam_type',
            field=models.CharField(choices=[], max_length=20, verbose_name='Тип экзамена'),
        ),
        migrations.AlterField(
            model_name='fipisourcemap',
            name='file_format',
            field=models.CharField(choices=[], default='HTML', max_length=10, verbose_name='Формат файла'),
        ),
        migrations.AlterField(
            model_name='fipisourcemap',
            name='priority',
            field=models.IntegerField(choices=[], default=3, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='fipisourcemap',
            name='update_frequency',
            field=models.CharField(choices=[], default='annually', max_length=20, verbose_name='Частота обновления'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='exam_type',
            field=models.CharField(choices=[], max_length=20, verbose_name='Тип экзамена'),
        ),
        migrations.AlterField(
            model_name='subscriptionlimit',
            name='subscription_type',
            field=models.CharField(choices=[], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='difficulty_preference',
            field=models.CharField(choices=[], default='medium', max_length=20, verbose_name='Предпочитаемая сложность'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='subscription_type',
            field=models.CharField(choices=[], default='free', max_length=20, verbose_name='Тип подписки'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='subscription_type',
            field=models.CharField(choices=[], default='free', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
