# Generated by Django 4.2.7 on 2025-08-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        # Добавляем поле exam_type в таблицу learning_subject если его нет
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name = 'learning_subject' 
                    AND column_name = 'exam_type'
                ) THEN
                    ALTER TABLE learning_subject 
                    ADD COLUMN exam_type VARCHAR(3) DEFAULT 'ЕГЭ' 
                    CHECK (exam_type IN ('ЕГЭ', 'ОГЭ'));
                END IF;
            END $$;
            """,
            reverse_sql="""
            ALTER TABLE learning_subject DROP COLUMN IF EXISTS exam_type;
            """
        ),
        
        # Добавляем поле code в таблицу learning_topic если его нет
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name = 'learning_topic' 
                    AND column_name = 'code'
                ) THEN
                    ALTER TABLE learning_topic 
                    ADD COLUMN code VARCHAR(20) DEFAULT '';
                END IF;
            END $$;
            """,
            reverse_sql="""
            ALTER TABLE learning_topic DROP COLUMN IF EXISTS code;
            """
        ),
    ]



