# Generated by Django 4.2.7 on 2025-08-25 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0002_add_missing_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_userprogress_set', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
