# Generated by Django 4.2.7 on 2025-09-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0006_add_subject_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subject",
            options={
                "ordering": ["is_primary", "name"],
                "verbose_name": "Предмет",
                "verbose_name_plural": "Предметы",
            },
        ),
        migrations.AlterField(
            model_name="subject",
            name="code",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Код предмета"
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="subject",
            name="icon",
            field=models.CharField(blank=True, default="", max_length=100, verbose_name="Иконка"),
        ),
        migrations.AlterField(
            model_name="subject",
            name="is_archived",
            field=models.BooleanField(default=False, verbose_name="Архивирован"),
        ),
        migrations.AlterField(
            model_name="subject",
            name="is_primary",
            field=models.BooleanField(default=False, verbose_name="Основной предмет"),
        ),
    ]
