# Generated by Django 4.2.7 on 2025-09-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_alter_subject_options_alter_subject_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='exam_type',
            field=models.CharField(choices=[], default='ЕГЭ', max_length=3, verbose_name='Тип экзамена'),
        ),
    ]
