# Generated by Django 4.2.7 on 2025-09-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0009_alter_subject_exam_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="exam_type",
            field=models.CharField(
                blank=True,
                choices=[("ege", "ЕГЭ"), ("oge", "ОГЭ"), ("other", "Другое")],
                default="ege",
                max_length=10,
                verbose_name="Тип экзамена",
            ),
        ),
    ]
