# Generated by Django 4.2.7 on 2025-09-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telegram_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="telegramuser",
            managers=[],
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="first_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="last_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="username",
            field=models.CharField(default="default", max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
