# Generated by Django 4.2.7 on 2025-08-20 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiPromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('template_type', models.CharField(choices=[('explanation', 'Объяснение темы'), ('task_search', 'Поиск заданий'), ('task_generation', 'Генерация заданий'), ('question', 'Ответ на вопрос'), ('recommendation', 'Рекомендации'), ('motivation', 'Мотивация'), ('solution_analysis', 'Анализ решения')], max_length=20)),
                ('prompt_template', models.TextField()),
                ('variables', models.JSONField(default=dict, help_text='Переменные для подстановки в шаблон')),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Шаблон промпта',
                'verbose_name_plural': 'Шаблоны промптов',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AiProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('provider_type', models.CharField(choices=[('deepseek', 'DeepSeek Chat'), ('gigachat', 'GigaChat'), ('llama', 'LLaMA (локальный)'), ('falcon', 'Falcon (локальный)'), ('fallback', 'Fallback (резервный)')], max_length=20)),
                ('api_key', models.CharField(blank=True, max_length=500)),
                ('api_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=1)),
                ('daily_limit', models.IntegerField(default=1000)),
                ('daily_usage', models.IntegerField(default=0)),
                ('cost_per_token', models.DecimalField(decimal_places=8, default=0, max_digits=10)),
                ('max_tokens_per_request', models.IntegerField(default=4000)),
                ('response_time_avg', models.FloatField(default=0)),
                ('success_rate', models.FloatField(default=100)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Провайдер ИИ',
                'verbose_name_plural': 'Провайдеры ИИ',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AiResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_hash', models.CharField(max_length=64, unique=True)),
                ('prompt', models.TextField()),
                ('response', models.TextField()),
                ('tokens_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('usage_count', models.IntegerField(default=1)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai.aiprovider')),
            ],
            options={
                'verbose_name': 'Ответ ИИ',
                'verbose_name_plural': 'Ответы ИИ',
                'ordering': ['-last_used'],
            },
        ),
        migrations.CreateModel(
            name='AiRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('request_type', models.CharField(choices=[('explanation', 'Объяснение темы'), ('task_search', 'Поиск заданий'), ('task_generation', 'Генерация заданий'), ('question', 'Вопрос по подготовке'), ('recommendation', 'Персональные рекомендации'), ('motivation', 'Мотивация'), ('solution_analysis', 'Анализ решения')], max_length=50)),
                ('prompt', models.TextField()),
                ('response', models.TextField()),
                ('tokens_used', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запрос к ИИ',
                'verbose_name_plural': 'Запросы к ИИ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AiLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('limit_type', models.CharField(choices=[('daily', 'Дневной лимит'), ('monthly', 'Месячный лимит'), ('total', 'Общий лимит')], max_length=20)),
                ('current_usage', models.IntegerField(default=0)),
                ('max_limit', models.IntegerField()),
                ('reset_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лимит ИИ',
                'verbose_name_plural': 'Лимиты ИИ',
                'unique_together': {('user', 'session_id', 'limit_type')},
            },
        ),
    ]
