# Generated by Django 4.2.7 on 2025-09-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ailimit',
            name='limit_type',
            field=models.CharField(choices=[], max_length=20),
        ),
        migrations.AlterField(
            model_name='aiprompttemplate',
            name='template_type',
            field=models.CharField(choices=[], max_length=20),
        ),
        migrations.AlterField(
            model_name='aiprovider',
            name='provider_type',
            field=models.CharField(choices=[], max_length=20),
        ),
        migrations.AlterField(
            model_name='airequest',
            name='request_type',
            field=models.CharField(choices=[], max_length=50),
        ),
    ]
