# Generated by Django 4.2.7 on 2025-09-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0002_alter_ailimit_limit_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ailimit",
            name="limit_type",
            field=models.CharField(choices=[], default="daily", max_length=20),
        ),
    ]
