line-length = 120
target-version = "py311"

[lint]
select = [
  "E",  # pycodestyle errors
  "F",  # pyflakes
  "I",  # isort
]
ignore = [
  "E501",  # длинные строки
  "W503",  # line break before binary operator
  "E203",  # whitespace before ':'
]

[format]
quote-style = "single"
indent-style = "space"

