CSP_DEFAULT_SRC = ("'self'", )
CSP_SCRIPT_SRC = ("'self'", "'unsafe-inline'", "'unsafe-eval'")
CSP_STYLE_SRC = ("'self'", "'unsafe-inline'", )
CSP_IMG_SRC = ("'self'", 'data:', )
CSP_CONNECT_SRC = ("'self'", )
CSP_FRAME_ANCESTORS = ("'none'", )
