name: CI - Lint & Django checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Flake8 (PEP8)
        run: |
          python -m pip install flake8
          # Базовая проверка основных модулей; допускаем длинные строки и спорные правила
          flake8 --max-line-length=120 --ignore=E501,W503,E203,F401 core/ learning/ examflow_project/ telegram_bot/

      - name: Django system check
        env:
          DJANGO_SETTINGS_MODULE: examflow_project.settings
        run: |
          python manage.py check --deploy --fail-level WARNING

      - name: Collect static (dry run)
        env:
          DJANGO_SETTINGS_MODULE: examflow_project.settings
        run: |
          python manage.py collectstatic --noinput --dry-run


