name: ExamFlow 2.0 Keepalive

on:
  schedule:
    # Запускается каждые 10 минут для поддержания активности
    - cron: '*/10 * * * *'
  workflow_dispatch: # Позволяет запускать вручную

jobs:
  keepalive:
    runs-on: ubuntu-latest
    
    steps:
    - name: Wake up ExamFlow website
      run: |
        echo "🌐 Пробуждаем ExamFlow 2.0..."
        curl -s -o /dev/null -w "%{http_code}" https://examflow.ru/health/
        echo "✅ Keepalive выполнен"
    
    - name: Wake up Telegram bot
      run: |
        echo "🤖 Проверяем Telegram бота..."
        curl -s -o /dev/null -w "%{http_code}" https://examflow.ru/health/
        echo "✅ Бот активен"
    
    - name: Log keepalive status
      run: |
        echo "🕐 Keepalive выполнен в $(date)"
        echo "🌐 Сайт: https://examflow.ru"
        echo "🤖 Бот: @examflow_bot"

