name: ♻️ KeepAlive Render

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: 🔗 Пинг главной страницы
        run: |
          curl -sS -m 20 https://examflow.ru/ -o /dev/null -w "%{http_code}\n"
      - name: 🔗 Пинг ИИ-страницы (разбудить Django)
        run: |
          curl -sS -m 20 https://examflow.ru/ai/chat/ -o /dev/null -w "%{http_code}\n"

