name: ExamFlow 2.0 Enhanced Keepalive

on:
  schedule:
    # Запускается каждые 5 минут для максимальной активности
    - cron: '*/5 * * * *'
  workflow_dispatch: # Позволяет запускать вручную
  push:
    branches: [ main ]
    paths:
      - 'core/keepalive_service.py'
      - 'core/health_check.py'
      - '.github/workflows/keepalive-enhanced.yml'

jobs:
  keepalive:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests psutil
    
    - name: Wake up ExamFlow website
      run: |
        echo "🌐 Пробуждаем ExamFlow 2.0..."
        
        # Проверяем основной сайт
        echo "Проверяем https://examflow.ru..."
        curl -s -o /dev/null -w "Status: %{http_code}, Time: %{time_total}s\n" https://examflow.ru/
        
        # Проверяем health check
        echo "Проверяем health check..."
        curl -s -o /dev/null -w "Status: %{http_code}, Time: %{time_total}s\n" https://examflow.ru/health/
        
        # Проверяем простой health check
        echo "Проверяем simple health check..."
        curl -s -o /dev/null -w "Status: %{http_code}, Time: %{time_total}s\n" https://examflow.ru/health/simple/
        
        # Проверяем основные страницы
        echo "Проверяем основные страницы..."
        curl -s -o /dev/null -w "Features: %{http_code}\n" https://examflow.ru/features/
        curl -s -o /dev/null -w "Pricing: %{http_code}\n" https://examflow.ru/pricing/
        curl -s -o /dev/null -w "Subjects: %{http_code}\n" https://examflow.ru/learning/subjects/
        
        echo "✅ Keepalive выполнен"
    
    - name: Wake up Telegram bot
      run: |
        echo "🤖 Проверяем Telegram бота..."
        
        # Проверяем webhook бота
        echo "Проверяем webhook бота..."
        curl -s -o /dev/null -w "Bot webhook: %{http_code}\n" https://examflow.ru/bot/webhook/
        
        # Проверяем API статус бота
        echo "Проверяем API статус бота..."
        curl -s -o /dev/null -w "Bot API: %{http_code}\n" https://examflow.ru/bot/api/status/
        
        echo "✅ Бот проверен"
    
    - name: Test database connectivity
      run: |
        echo "🗄️ Тестируем подключение к базе данных..."
        
        # Проверяем эндпоинты, которые используют базу данных
        echo "Проверяем API задач..."
        curl -s -o /dev/null -w "Tasks API: %{http_code}\n" https://examflow.ru/api/tasks/random/
        
        echo "Проверяем API предметов..."
        curl -s -o /dev/null -w "Subjects API: %{http_code}\n" https://examflow.ru/api/subjects/
        
        echo "✅ База данных проверена"
    
    - name: Test AI services
      run: |
        echo "🤖 Тестируем ИИ сервисы..."
        
        # Проверяем AI чат
        echo "Проверяем AI чат..."
        curl -s -o /dev/null -w "AI Chat: %{http_code}\n" https://examflow.ru/ai/chat/
        
        echo "✅ ИИ сервисы проверены"
    
    - name: Performance check
      run: |
        echo "⚡ Проверяем производительность..."
        
        # Измеряем время ответа
        echo "Измеряем время ответа главной страницы..."
        RESPONSE_TIME=$(curl -s -o /dev/null -w "%{time_total}" https://examflow.ru/)
        echo "Время ответа: ${RESPONSE_TIME}s"
        
        # Проверяем, что время ответа приемлемое (менее 10 секунд)
        if (( $(echo "$RESPONSE_TIME < 10" | bc -l) )); then
          echo "✅ Производительность в норме"
        else
          echo "⚠️ Медленный ответ: ${RESPONSE_TIME}s"
        fi
    
    - name: Log keepalive status
      run: |
        echo "🕐 Keepalive выполнен в $(date)"
        echo "🌐 Сайт: https://examflow.ru"
        echo "🤖 Бот: @ExamFlowBot"
        echo "📊 Health Check: https://examflow.ru/health/"
        echo "🔧 Simple Health: https://examflow.ru/health/simple/"
    
    - name: Notify on failure
      if: failure()
      run: |
        echo "❌ Keepalive failed at $(date)"
        echo "Проверьте логи Render Dashboard"
        echo "URL: https://dashboard.render.com"
